version: '3.8'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: iepure_MQ
        ports:
            - "5672:5672"
            - "15672:15672"

    ftp_server:
        image: stilliard/pure-ftpd:hardened
        container_name: ftp_server
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        environment:
            - PUBLICHOST=localhost
            - FTP_USER_NAME=ftpuser
            - FTP_USER_PASS=ftppass
            - FTP_USER_HOME=/home/ftpusers
        volumes:
            - ./ftp_data:/home/ftpusers