"""db

Revision ID: d2db1436de07
Revises: 
Create Date: 2024-10-28 11:39:22.134341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2db1436de07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capacit_motor', sa.String(), nullable=True),
    sa.Column('tip_combustibil', sa.String(), nullable=True),
    sa.Column('anul_fabricatiei', sa.String(), nullable=True),
    sa.Column('cutia_de_viteze', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelul', sa.String(), nullable=True),
    sa.Column('tip_tractiune', sa.String(), nullable=True),
    sa.Column('distanta_parcursa', sa.String(), nullable=True),
    sa.Column('tip_caroserie', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
